site_name: Societies Docs
pages:
        - [index.md, Home]
        - [install.md, Installation]
        - [mechanics.md, Mechanics]
        - [permissions.md, Permissions]  
        - [commands.md, Commands]
        - [chat.md, Chat]
        - [economy.md, Economy]
        - [persistance.md, Persistance]
        - [translation.md, Translation]
theme: readthedocs
repo_url: https://github.com/mc-societies/societies
site_author: Max Ammann

